import React from 'react';
import {
  AbsoluteFill,
  Img,
  Sequence,
  Easing,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';

const C = { canvas: '#fdfcfc', ink: '#201d1d', muted: '#646262', accent: '#007aff', line: '#d8d6d3', blueSoft: '#eaf3ff', green: '#1f9d73', amber: '#c8891b' };
const mono = 'IBM Plex Mono, Berkeley Mono, monospace';
const sans = 'IBM Plex Sans, -apple-system, BlinkMacSystemFont, sans-serif';
const SHOTS = { open: [0, 90], ingest: [90, 210], graph: [210, 390], diagnose: [390, 540], simulator: [540, 660], evidence: [660, 780], migration: [780, 870], market: [870, 960], admin: [960, 1020], close: [1020, 1140] } as const;

const fade = (frame: number, start = 0, end = 18) => interpolate(frame, [start, end], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
const SlideTitle: React.FC<{ kicker: string; title: string; detail?: string }> = ({ kicker, title, detail }) => (
  <div style={{ position: 'absolute', left: 78, top: 64, zIndex: 3 }}>
    <div style={{ fontFamily: mono, fontSize: 16, letterSpacing: 2, color: C.accent, textTransform: 'uppercase' }}>{kicker}</div>
    <div style={{ fontFamily: sans, fontWeight: 600, fontSize: 48, color: C.ink, marginTop: 12 }}>{title}</div>
    {detail && <div style={{ fontFamily: sans, fontSize: 22, color: C.muted, marginTop: 12 }}>{detail}</div>}
  </div>
);
const Grid: React.FC = () => <div style={{ position: 'absolute', inset: 0, opacity: 0.45, backgroundImage: `linear-gradient(${C.line}55 1px, transparent 1px), linear-gradient(90deg, ${C.line}55 1px, transparent 1px)`, backgroundSize: '64px 64px' }} />;
const Screen: React.FC<{ src: string; x?: number; y?: number; w?: number; scale?: number; rotate?: number; opacity?: number }> = ({ src, x = 250, y = 200, w = 1420, scale = 1, rotate = 0, opacity = 1 }) => (
  <div style={{ position: 'absolute', left: x, top: y, width: w, opacity, transform: `scale(${scale}) rotate(${rotate}deg)`, transformOrigin: 'center', border: `1px solid ${C.line}`, boxShadow: '0 28px 80px rgba(32,29,29,.16)', background: C.canvas }}>
    <div style={{ height: 30, borderBottom: `1px solid ${C.line}`, display: 'flex', alignItems: 'center', padding: '0 14px', gap: 6 }}><i style={{ width: 8, height: 8, borderRadius: 8, background: '#ff6b6b' }} /><i style={{ width: 8, height: 8, borderRadius: 8, background: '#ffc857' }} /><i style={{ width: 8, height: 8, borderRadius: 8, background: '#5ac878' }} /></div>
    <Img src={staticFile(`textures/${src}`)} style={{ display: 'block', width: '100%' }} />
  </div>
);

const BrandOpen: React.FC = () => { const f = useCurrentFrame(); const s = spring({ frame: f, fps: 30, config: { damping: 200 } }); return <AbsoluteFill style={{ background: C.ink, color: C.canvas, justifyContent: 'center', alignItems: 'center' }}><Grid /><div style={{ position: 'relative', textAlign: 'center', opacity: fade(f, 4, 26), transform: `scale(${.88 + .12 * s})` }}><div style={{ fontFamily: sans, fontWeight: 600, fontSize: 104, letterSpacing: -4 }}>智演</div><div style={{ fontFamily: mono, fontSize: 26, letterSpacing: 5, color: '#b9c5d4', marginTop: 18 }}>JOBEVOLUTION</div><div style={{ width: 110, height: 4, background: C.accent, margin: '34px auto 0' }} /></div></AbsoluteFill>; };

const Ingest: React.FC = () => { const f = useCurrentFrame(); const rows = ['Agent工程师', '大模型应用工程师', '机器学习工程师', '模型评测工程师', '数据工程师', '机器人软件工程师']; return <AbsoluteFill style={{ background: C.canvas }}><Grid /><SlideTitle kicker="01 / discover" title="把招聘数据变成可对账的岗位图谱" detail="官方 JD 进入同一套岗位事实管线" /><div style={{ position: 'absolute', left: 110, top: 285, width: 480, padding: 28, border: `1px solid ${C.line}`, background: '#fff', opacity: fade(f, 12, 28) }}><div style={{ fontFamily: mono, fontSize: 15, color: C.muted }}>SOURCE / OFFICIAL PORTALS</div>{rows.slice(0, 3).map((r, i) => <div key={r} style={{ marginTop: 22, padding: '16px 18px', border: `1px solid ${C.line}`, fontFamily: sans, fontSize: 21, transform: `translateX(${interpolate(f, [20 + i * 8, 45 + i * 8], [-80, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) })}px)`, opacity: fade(f, 20 + i * 8, 34 + i * 8) }}>{r}<span style={{ float: 'right', color: C.green }}>已采集</span></div>)}</div><div style={{ position: 'absolute', left: 690, top: 448, fontSize: 64, color: C.accent, opacity: fade(f, 32, 50) }}>→</div><div style={{ position: 'absolute', right: 120, top: 285, width: 600, height: 350, border: `1px solid ${C.accent}`, background: C.blueSoft, padding: 30, opacity: fade(f, 36, 54) }}><div style={{ fontFamily: mono, fontSize: 15, color: C.accent }}>GRAPH / ROLE FACTS</div><div style={{ fontFamily: sans, fontSize: 34, fontWeight: 600, marginTop: 30 }}>岗位定义 · 要求边 · 证据</div><div style={{ display: 'flex', gap: 12, marginTop: 34 }}>{['17 个岗位靶子', '4 个领域', '持续差分'].map(t => <span key={t} style={{ padding: '10px 14px', border: `1px solid ${C.accent}66`, fontFamily: mono, fontSize: 14 }}>{t}</span>)}</div></div></AbsoluteFill>; };

const Graph: React.FC = () => { const f = useCurrentFrame(); return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="02 / map" title="看见岗位要求如何变化" detail="每条技能边都能回到原始招聘证据" /><Screen src="graph-full.png" x={230} y={215} w={1460} scale={interpolate(f, [0, 160], [1.04, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })} opacity={fade(f, 10, 28)} /><div style={{ position: 'absolute', right: 116, top: 730, padding: '14px 18px', color: C.canvas, background: C.ink, fontFamily: mono, fontSize: 16, opacity: fade(f, 80, 100) }}>切片差分 / 本周期新增要求</div></AbsoluteFill>; };

const Diagnose: React.FC = () => { const f = useCurrentFrame(); return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="03 / diagnose" title="从简历出发，找到下一步" detail="校对证据，再比较两个可诊断岗位" /><Screen src="diagnose-full.png" x={360} y={210} w={1200} scale={interpolate(f, [0, 140], [1.05, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })} opacity={fade(f, 6, 24)} /><div style={{ position: 'absolute', bottom: 85, left: 370, display: 'flex', gap: 14, opacity: fade(f, 65, 82) }}>{['上传简历', '校对解析', '选两个岗位', '得到方向结论'].map((t, i) => <div key={t} style={{ padding: '12px 18px', background: i === 3 ? C.accent : '#fff', color: i === 3 ? '#fff' : C.ink, border: `1px solid ${i === 3 ? C.accent : C.line}`, fontFamily: mono, fontSize: 15 }}>{String(i + 1).padStart(2, '0')} {t}</div>)}</div></AbsoluteFill>; };

const Simulator: React.FC = () => { const f = useCurrentFrame(); const a = Math.round(interpolate(f, [10, 70], [45, 68], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) })); const b = Math.round(interpolate(f, [50, 112], [68, 82], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic) })); return <AbsoluteFill style={{ background: C.ink, color: C.canvas }}><Grid /><div style={{ position: 'relative', margin: 'auto', width: 1300 }}><div style={{ fontFamily: mono, color: '#9db8d2', fontSize: 16, letterSpacing: 2 }}>04 / MOVE</div><div style={{ fontFamily: sans, fontSize: 58, fontWeight: 600, marginTop: 16 }}>把缺口变成可执行的换档条件</div><div style={{ display: 'flex', alignItems: 'center', gap: 46, marginTop: 90 }}><div><div style={{ fontFamily: mono, color: '#b9c5d4', fontSize: 18 }}>当前岗位</div><div style={{ fontFamily: mono, fontSize: 112, color: '#fff', marginTop: 12 }}>{a}%</div></div><div style={{ fontSize: 70, color: C.accent }}>→</div><div><div style={{ fontFamily: mono, color: '#b9c5d4', fontSize: 18 }}>补齐证据后</div><div style={{ fontFamily: mono, fontSize: 112, color: '#69b1ff', marginTop: 12 }}>{b}%</div></div><div style={{ borderLeft: '1px solid #ffffff44', paddingLeft: 40, fontFamily: sans, fontSize: 24, lineHeight: 1.6, color: '#d7dee8' }}>不是一个总分。<br />是一组有证据的下一步。</div></div></div></AbsoluteFill>; };

const Evidence: React.FC = () => { const f = useCurrentFrame(); const lines = [{ y: 310, t: 'Python / FastAPI', c: C.green }, { y: 405, t: 'RAG / 向量数据库', c: C.accent }, { y: 500, t: '评测集构建', c: C.amber }]; return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="05 / evidence" title="每个判断，都留着证据" detail="原文片段、岗位要求和证据级别一一对应" /><div style={{ position: 'absolute', left: 140, top: 270, width: 540, padding: 30, border: `1px solid ${C.line}`, background: '#fff', opacity: fade(f, 8, 24) }}><div style={{ fontFamily: mono, fontSize: 15, color: C.muted }}>RESUME / EXPERIENCE</div><div style={{ fontFamily: sans, fontSize: 28, lineHeight: 1.8, marginTop: 28 }}>负责服务编排与检索链路，<br />上线后延迟下降 32%。</div></div><div style={{ position: 'absolute', left: 790, top: 270, width: 820, height: 330, border: `1px solid ${C.line}`, background: '#fff' }}>{lines.map((l, i) => <React.Fragment key={l.t}><div style={{ position: 'absolute', left: 0, top: l.y - 270, width: 820, height: 1, background: l.c, transformOrigin: 'left', transform: `scaleX(${interpolate(f, [18 + i * 14, 38 + i * 14], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })})` }} /><div style={{ position: 'absolute', left: 28, top: l.y - 255, fontFamily: mono, fontSize: 18, color: l.c, opacity: fade(f, 18 + i * 14, 34 + i * 14) }}>{l.t}</div></React.Fragment>)}</div></AbsoluteFill>; };

const Migration: React.FC = () => { const f = useCurrentFrame(); const cards = [{ title: '大模型应用工程师', body: '已有证据 6 项', accent: C.accent }, { title: 'Agent 工程师', body: '补齐评测与工具调用', accent: C.amber }, { title: '模型评测工程师', body: '最小换档条件 3 项', accent: C.green }]; return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="06 / compare" title="比较邻近岗位，而不是猜一个答案" detail="方向结论给出理由，也保留证据不足" /><div style={{ display: 'flex', gap: 18, position: 'absolute', left: 190, top: 300 }}>{cards.map((c, i) => <div key={c.title} style={{ width: 420, height: 310, background: '#fff', border: `1px solid ${c.accent}`, padding: 28, opacity: fade(f, 12 + i * 12, 28 + i * 12), transform: `translateY(${interpolate(f, [12 + i * 12, 32 + i * 12], [70, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })}px)` }}><div style={{ fontFamily: mono, color: c.accent, fontSize: 15 }}>ROLE 0{i + 1}</div><div style={{ fontFamily: sans, fontSize: 28, fontWeight: 600, marginTop: 32 }}>{c.title}</div><div style={{ fontFamily: sans, fontSize: 19, color: C.muted, marginTop: 54 }}>{c.body}</div><div style={{ position: 'absolute', left: 28, right: 28, bottom: 24, height: 6, background: `${c.accent}22` }}><div style={{ width: `${55 + i * 13}%`, height: '100%', background: c.accent }} /></div></div>)}</div></AbsoluteFill>; };

const Market: React.FC = () => { const f = useCurrentFrame(); const rows = [['2026.08.28', '评测集构建', '+1'], ['2026.08.19', '工具调用', '+2'], ['2026.08.04', '多模态输入', '新出现'], ['2026.07.21', '向量数据库', '持续']]; return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="07 / signal" title="追踪岗位要求怎么变" detail="用周期差分替代静态 JD 印象" /><div style={{ position: 'absolute', left: 190, right: 190, top: 280, fontFamily: mono, borderTop: `1px solid ${C.line}` }}>{rows.map((r, i) => <div key={r[0]} style={{ display: 'grid', gridTemplateColumns: '240px 1fr 180px', alignItems: 'center', padding: '24px 18px', borderBottom: `1px solid ${C.line}`, opacity: fade(f, 10 + i * 9, 25 + i * 9), transform: `translateX(${interpolate(f, [10 + i * 9, 28 + i * 9], [80, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })}px)` }}><span style={{ color: C.muted }}>{r[0]}</span><span style={{ fontFamily: sans, fontSize: 28 }}>{r[1]}</span><span style={{ color: i === 2 ? C.accent : C.green, textAlign: 'right' }}>{r[2]}</span></div>)}</div></AbsoluteFill>; };

const Admin: React.FC = () => { const f = useCurrentFrame(); return <AbsoluteFill style={{ background: C.canvas }}><SlideTitle kicker="08 / review" title="让审核成为最后一道闸" detail="高置信事实自动通过，其余进入待审队列" /><Screen src="admin-full.png" x={310} y={230} w={1300} scale={interpolate(f, [0, 52], [1.04, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })} opacity={fade(f, 4, 18)} /><div style={{ position: 'absolute', right: 150, bottom: 80, padding: '12px 18px', background: C.ink, color: C.canvas, fontFamily: mono, fontSize: 15, opacity: fade(f, 20, 36) }}>review gate / audit trail</div></AbsoluteFill>; };

const BrandClose: React.FC = () => { const f = useCurrentFrame(); return <AbsoluteFill style={{ background: C.ink, color: C.canvas, justifyContent: 'center', alignItems: 'center' }}><Grid /><div style={{ textAlign: 'center', opacity: fade(f, 8, 30) }}><div style={{ fontFamily: sans, fontWeight: 600, fontSize: 88 }}>智演 <span style={{ color: '#9db8d2' }}>JobEvolution</span></div><div style={{ fontFamily: sans, fontSize: 30, color: '#d7dee8', marginTop: 22 }}>让职业选择跟上岗位变化</div><div style={{ fontFamily: mono, fontSize: 16, letterSpacing: 3, color: '#8da4bb', marginTop: 46 }}>DATA → EVIDENCE → NEXT MOVE</div></div></AbsoluteFill>; };

export const PromoVideo: React.FC = () => <>{([['open', BrandOpen], ['ingest', Ingest], ['graph', Graph], ['diagnose', Diagnose], ['simulator', Simulator], ['evidence', Evidence], ['migration', Migration], ['market', Market], ['admin', Admin], ['close', BrandClose]] as const).map(([name, Component]) => { const [from, end] = SHOTS[name]; return <Sequence key={name} from={from} durationInFrames={end - from}><Component /></Sequence>; })}</>;
